{{- $default := .Values.controller.defaultSSLCertificate }}
{{- $cm := $default.certManager }}
{{- if and $default.enabled $cm.enabled $cm.createIssuer (.Capabilities.APIVersions.Has "cert-manager.io/v1") }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "haptic.fullname" . }}-ssl-selfsigned
  namespace: {{ $default.namespace | default .Release.Namespace }}
  labels:
    {{- include "haptic.labels" . | nindent 4 }}
  annotations:
    description: "HAPTIC Dummy Issuer - For development/testing only. Override for production."
spec:
  selfSigned: {}
{{- end }}
