{{- $items := .Values.extraDeploy }}
{{- if kindIs "map" $items }}{{- $items = values $items }}{{- end }}
{{- range $items }}
---
{{ if typeIs "string" . }}
{{- tpl . $ }}
{{- else }}
{{- tpl (toYaml .) $ }}
{{- end }}
{{- end }}
