{{- $items := list }}
{{- if kindIs "map" .Values.extraDeploy }}
{{- range $key, $val := .Values.extraDeploy }}
{{- $items = append $items $val }}
{{- end }}
{{- else }}
{{- $items = .Values.extraDeploy }}
{{- end }}
{{- range $items }}
---
{{ if typeIs "string" . }}
{{- tpl . $ }}
{{- else }}
{{- tpl (toYaml .) $ }}
{{- end }}
{{- end }}
