{{- if .Values.haproxy.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "haptic.haproxyFullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "haptic.labels" . | nindent 4 }}
    app.kubernetes.io/component: loadbalancer
data:
  haproxy.cfg: |
    {{- tpl (.Values.haproxy.initialConfig | default "") . | nindent 4 }}
{{- end }}
