{{- $keda := .Values.haproxy.keda }}
{{- if and .Values.haproxy.enabled $keda.enabled }}
{{- $haproxyFullname := include "haptic.haproxyFullname" . }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ $haproxyFullname }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "haptic.labels.withCommon" . | nindent 4 }}
    app.kubernetes.io/component: loadbalancer
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $haproxyFullname }}
  pollingInterval: {{ $keda.pollingInterval }}
  cooldownPeriod: {{ $keda.cooldownPeriod }}
  minReplicaCount: {{ $keda.minReplicaCount }}
  maxReplicaCount: {{ $keda.maxReplicaCount }}
  {{- with $keda.fallback }}
  fallback:
    failureThreshold: {{ .failureThreshold }}
    replicas: {{ .replicas }}
  {{- end }}
  {{- with $keda.advanced }}
  advanced:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  triggers:
    {{- toYaml $keda.triggers | nindent 4 }}
{{- end }}
