{{- $as := .Values.autoscaling }}
{{- if $as.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "haptic.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "haptic.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "haptic.controllerFullname" . }}
  minReplicas: {{ $as.minReplicas }}
  maxReplicas: {{ $as.maxReplicas }}
  metrics:
    {{- range $name, $valuesKey := dict "cpu" "targetCPUUtilizationPercentage" "memory" "targetMemoryUtilizationPercentage" }}
    {{- with index $as $valuesKey }}
    - type: Resource
      resource:
        name: {{ $name }}
        target:
          type: Utilization
          averageUtilization: {{ . }}
    {{- end }}
    {{- end }}
{{- end }}
