{{- $ic := .Values.ingressClass }}
{{- if and $ic.enabled .Values.controller.templateLibraries.ingress.enabled (.Capabilities.APIVersions.Has "networking.k8s.io/v1/IngressClass") }}
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: {{ $ic.name }}
  labels:
    {{- include "haptic.labels" . | nindent 4 }}
  {{- if $ic.default }}
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
  {{- end }}
spec:
  controller: {{ $ic.controllerName }}
{{- end }}
