{{- $pdb := .Values.controller.podDisruptionBudget }}
{{- if and $pdb.enabled (gt (.Values.controller.replicaCount | int) 1) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "haptic.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "haptic.labels" . | nindent 4 }}
spec:
  {{- with $pdb.minAvailable }}
  minAvailable: {{ . }}
  {{- end }}
  {{- with $pdb.maxUnavailable }}
  maxUnavailable: {{ . }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "haptic.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: controller
{{- end }}
