{{- $sa := .Values.serviceAccount }}
{{- if $sa.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "haptic.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "haptic.labels.withCommon" . | nindent 4 }}
  {{- if or $sa.annotations .Values.commonAnnotations }}
  annotations:
    {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with $sa.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
automountServiceAccountToken: {{ $sa.automount }}
{{- end }}
