{{- $svc := .Values.controller.service }}
{{- $ports := .Values.controller.ports }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "haptic.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "haptic.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
  {{- with $svc.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ $svc.type }}
  {{- with $svc.clusterIP }}
  clusterIP: {{ . }}
  {{- end }}
  {{- with $svc.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with $svc.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $svc.loadBalancerClass }}
  loadBalancerClass: {{ . }}
  {{- end }}
  {{- with $svc.externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
  {{- with $svc.internalTrafficPolicy }}
  internalTrafficPolicy: {{ . }}
  {{- end }}
  {{- with $svc.sessionAffinity }}
  sessionAffinity: {{ . }}
  {{- end }}
  {{- with $svc.sessionAffinityConfig }}
  sessionAffinityConfig:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  ports:
    {{- range $name := list "healthz" "metrics" }}
    {{- if gt (int (index $ports $name)) 0 }}
    - port: {{ index $ports $name }}
      targetPort: {{ $name }}
      protocol: TCP
      name: {{ $name }}
    {{- end }}
    {{- end }}
  selector:
    {{- include "haptic.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: controller
