# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2
project_name: haptic

# Snapshot configuration for CI builds (goreleaser release --snapshot)
# Produces images with CI-specific tags: ci-<pipeline_id>-haproxy<version>
snapshot:
  version_template: "ci-{{ .Env.CI_PIPELINE_ID }}"

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: controller
    main: ./cmd/controller
    binary: haptic-controller
    env:
      - CGO_ENABLED=0
    # Reproducible build flags
    flags:
      - -trimpath
      - -buildvcs=false
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.CommitDate}}
    # Use commit timestamp for reproducibility
    mod_timestamp: "{{ .CommitTimestamp }}"

# No archives - attach raw binaries directly
archives:
  - formats: [binary]
    name_template: >-
      haptic-controller-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}

checksum:
  name_template: checksums.txt
  algorithm: sha256

# Cosign keyless signing for supply chain security (cosign v3 bundle format)
signs:
  - cmd: cosign
    signature: "${artifact}.sigstore.json"
    artifacts: checksum
    args:
      - sign-blob
      - --bundle=${signature}
      - ${artifact}
      - --yes

# Multi-arch Docker images using dockers_v2 (simpler than dockers + docker_manifests)
# Each entry builds a multi-arch manifest directly using docker buildx
# Note: dockers_v2 does NOT push images in snapshot mode by design (GoReleaser limitation)
# For CI builds, we use docker buildx directly; dockers_v2 is only used for releases
dockers_v2:
  # HAProxy 3.0
  - id: haproxy30
    ids: [controller]
    dockerfile: Dockerfile
    images:
      - "registry.gitlab.com/haproxy-template-ic/haproxy-template-ingress-controller"
    tags:
      - "{{ .Version }}-haproxy3.0"
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/arm/v7
    build_args:
      HAPROXY_VERSION: "3.0"
    flags:
      - "--target=runtime"
      - "--build-context=binary=."

  # HAProxy 3.1
  - id: haproxy31
    ids: [controller]
    dockerfile: Dockerfile
    images:
      - "registry.gitlab.com/haproxy-template-ic/haproxy-template-ingress-controller"
    tags:
      - "{{ .Version }}-haproxy3.1"
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/arm/v7
    build_args:
      HAPROXY_VERSION: "3.1"
    flags:
      - "--target=runtime"
      - "--build-context=binary=."

  # HAProxy 3.2 (default)
  - id: haproxy32
    ids: [controller]
    dockerfile: Dockerfile
    images:
      - "registry.gitlab.com/haproxy-template-ic/haproxy-template-ingress-controller"
    tags:
      - "{{ .Version }}-haproxy3.2"
      - "{{ .Version }}"
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/arm/v7
    build_args:
      HAPROXY_VERSION: "3.2"
    flags:
      - "--target=runtime"
      - "--build-context=binary=."

# Cosign keyless signing for Docker images
docker_signs:
  - cmd: cosign
    artifacts: all
    args:
      - sign
      - --yes
      - "${artifact}"

# Disable auto-generated changelog - use CHANGELOG.md instead
changelog:
  disable: true

# GitLab CI settings - use CI_JOB_TOKEN for authentication
gitlab_urls:
  use_job_token: true

release:
  gitlab:
    owner: haproxy-template-ic
    name: haproxy-template-ingress-controller

  # Automatically mark alpha/beta/rc versions as pre-release
  prerelease: auto

  # Release notes extracted from CHANGELOG.md
  header: |
    ## What's Changed

  # Attach binaries and signature bundle to release
  extra_files:
    - glob: ./dist/checksums.txt.sigstore.json
