extends: default

rules:
  line-length: disable
  document-start: disable
  truthy:
    check-keys: false
  comments:
    min-spaces-from-content: 1
  comments-indentation: disable
  indentation: disable
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1

ignore:
  - charts/haproxy-template-ic/templates/  # Helm templates contain Go template syntax
  - pkg/generated/
  - node_modules/
