#!/usr/bin/env bash
# Render the real chart-rendered haproxy.cfg + map files at N routes, using the
# repo COPY's `haptic validate --dump-rendered` over the benchmark
# validationTests generated by scripts/test-benchmark.sh --httproute-only.
#
# Prereq (run once):
#   cd repo-copy && KEEP_TEMP_DIR=$SPIKE/gen GENERATE_ONLY=1 \
#       ./scripts/test-benchmark.sh --httproute-only --steps 300,1000,3000
#   python3 fix-secret-ns.py $SPIKE/gen/benchmark-all.yaml
set -euo pipefail
SPIKE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SPIKE/repo-copy"
for n in "$@"; do
  echo "=== render $n ==="
  ./bin/haptic validate -f "$SPIKE/gen/benchmark-all.yaml" \
      --test "benchmark-httproute-$n" --dump-rendered --schema-dir tests/schemas \
      > "$SPIKE/gen/dump-$n.txt" 2>&1 || { tail -5 "$SPIKE/gen/dump-$n.txt"; exit 1; }
  python3 "$SPIKE/extract_rendered.py" "$SPIKE/gen/dump-$n.txt" "$SPIKE/gen/real-$n"
done
