// Copyright 2025 Philipp Hossner
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0

package events

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestNewDeploymentSkippedEvent_StoresAllFields(t *testing.T) {
	event := NewDeploymentSkippedEvent(3, "config_unchanged", "abc123", "def456")

	assert.Equal(t, 3, event.Total)
	assert.Equal(t, "config_unchanged", event.Reason)
	assert.Equal(t, "abc123", event.ConfigHash)
	assert.Equal(t, "def456", event.PodSetHash)
	assert.False(t, event.Timestamp().IsZero(), "timestamp should be set")
}

func TestNewDeploymentSkippedEvent_EventType(t *testing.T) {
	event := NewDeploymentSkippedEvent(0, "", "", "")

	assert.Equal(t, EventTypeDeploymentSkipped, event.EventType())
}

func TestNewDeploymentSkippedEvent_CorrelationPropagation(t *testing.T) {
	// Build a triggering event with a known correlation ID.
	triggering := &DeploymentScheduledEvent{
		Correlation: newCorrelation(WithCorrelation("test-corr-id", "test-causation-id")),
	}

	event := NewDeploymentSkippedEvent(
		1, "config_unchanged", "hash1", "hash2",
		PropagateCorrelation(triggering),
	)

	assert.Equal(t, "test-corr-id", event.CorrelationID(),
		"correlation ID should propagate from triggering event")
}

func TestNewDeploymentSkippedEvent_ZeroValues(t *testing.T) {
	event := NewDeploymentSkippedEvent(0, "", "", "")

	assert.Equal(t, 0, event.Total)
	assert.Equal(t, "", event.Reason)
	assert.Equal(t, "", event.ConfigHash)
	assert.Equal(t, "", event.PodSetHash)
	// EventID is always generated by newCorrelation(); correlationID stays
	// empty unless WithNewCorrelation()/WithCorrelation()/PropagateCorrelation
	// was passed. That matches every other event type in this package.
	assert.NotEmpty(t, event.EventID(), "event ID should always be generated")
	assert.Empty(t, event.CorrelationID(), "correlation ID stays empty without explicit options")
}
