//go:build !ignore_autogenerated

// Copyright 2025 Philipp Hossner
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuxiliaryFileReferences) DeepCopyInto(out *AuxiliaryFileReferences) {
	*out = *in
	if in.MapFiles != nil {
		in, out := &in.MapFiles, &out.MapFiles
		*out = make([]ResourceReference, len(*in))
		copy(*out, *in)
	}
	if in.SSLCertificates != nil {
		in, out := &in.SSLCertificates, &out.SSLCertificates
		*out = make([]ResourceReference, len(*in))
		copy(*out, *in)
	}
	if in.SSLCaFiles != nil {
		in, out := &in.SSLCaFiles, &out.SSLCaFiles
		*out = make([]ResourceReference, len(*in))
		copy(*out, *in)
	}
	if in.GeneralFiles != nil {
		in, out := &in.GeneralFiles, &out.GeneralFiles
		*out = make([]ResourceReference, len(*in))
		copy(*out, *in)
	}
	if in.CRTListFiles != nil {
		in, out := &in.CRTListFiles, &out.CRTListFiles
		*out = make([]ResourceReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuxiliaryFileReferences.
func (in *AuxiliaryFileReferences) DeepCopy() *AuxiliaryFileReferences {
	if in == nil {
		return nil
	}
	out := new(AuxiliaryFileReferences)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigPublishingConfig) DeepCopyInto(out *ConfigPublishingConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigPublishingConfig.
func (in *ConfigPublishingConfig) DeepCopy() *ConfigPublishingConfig {
	if in == nil {
		return nil
	}
	out := new(ConfigPublishingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControllerConfig) DeepCopyInto(out *ControllerConfig) {
	*out = *in
	in.LeaderElection.DeepCopyInto(&out.LeaderElection)
	out.ConfigPublishing = in.ConfigPublishing
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControllerConfig.
func (in *ControllerConfig) DeepCopy() *ControllerConfig {
	if in == nil {
		return nil
	}
	out := new(ControllerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataplaneConfig) DeepCopyInto(out *DataplaneConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataplaneConfig.
func (in *DataplaneConfig) DeepCopy() *DataplaneConfig {
	if in == nil {
		return nil
	}
	out := new(DataplaneConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GeneralFile) DeepCopyInto(out *GeneralFile) {
	*out = *in
	if in.PostProcessing != nil {
		in, out := &in.PostProcessing, &out.PostProcessing
		*out = make([]PostProcessorConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ReloadOnPush != nil {
		in, out := &in.ReloadOnPush, &out.ReloadOnPush
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GeneralFile.
func (in *GeneralFile) DeepCopy() *GeneralFile {
	if in == nil {
		return nil
	}
	out := new(GeneralFile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HAProxyCRTListFile) DeepCopyInto(out *HAProxyCRTListFile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HAProxyCRTListFile.
func (in *HAProxyCRTListFile) DeepCopy() *HAProxyCRTListFile {
	if in == nil {
		return nil
	}
	out := new(HAProxyCRTListFile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HAProxyCRTListFile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HAProxyCRTListFileList) DeepCopyInto(out *HAProxyCRTListFileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HAProxyCRTListFile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HAProxyCRTListFileList.
func (in *HAProxyCRTListFileList) DeepCopy() *HAProxyCRTListFileList {
	if in == nil {
		return nil
	}
	out := new(HAProxyCRTListFileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HAProxyCRTListFileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HAProxyCRTListFileSpec) DeepCopyInto(out *HAProxyCRTListFileSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HAProxyCRTListFileSpec.
func (in *HAProxyCRTListFileSpec) DeepCopy() *HAProxyCRTListFileSpec {
	if in == nil {
		return nil
	}
	out := new(HAProxyCRTListFileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HAProxyCRTListFileStatus) DeepCopyInto(out *HAProxyCRTListFileStatus) {
	*out = *in
	if in.DeployedToPods != nil {
		in, out := &in.DeployedToPods, &out.DeployedToPods
		*out = make([]PodDeploymentStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HAProxyCRTListFileStatus.
func (in *HAProxyCRTListFileStatus) DeepCopy() *HAProxyCRTListFileStatus {
	if in == nil {
		return nil
	}
	out := new(HAProxyCRTListFileStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HAProxyCfg) DeepCopyInto(out *HAProxyCfg) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HAProxyCfg.
func (in *HAProxyCfg) DeepCopy() *HAProxyCfg {
	if in == nil {
		return nil
	}
	out := new(HAProxyCfg)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HAProxyCfg) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HAProxyCfgList) DeepCopyInto(out *HAProxyCfgList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HAProxyCfg, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HAProxyCfgList.
func (in *HAProxyCfgList) DeepCopy() *HAProxyCfgList {
	if in == nil {
		return nil
	}
	out := new(HAProxyCfgList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HAProxyCfgList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HAProxyCfgSpec) DeepCopyInto(out *HAProxyCfgSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HAProxyCfgSpec.
func (in *HAProxyCfgSpec) DeepCopy() *HAProxyCfgSpec {
	if in == nil {
		return nil
	}
	out := new(HAProxyCfgSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HAProxyCfgStatus) DeepCopyInto(out *HAProxyCfgStatus) {
	*out = *in
	if in.DeployedToPods != nil {
		in, out := &in.DeployedToPods, &out.DeployedToPods
		*out = make([]PodDeploymentStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AuxiliaryFiles != nil {
		in, out := &in.AuxiliaryFiles, &out.AuxiliaryFiles
		*out = new(AuxiliaryFileReferences)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HAProxyCfgStatus.
func (in *HAProxyCfgStatus) DeepCopy() *HAProxyCfgStatus {
	if in == nil {
		return nil
	}
	out := new(HAProxyCfgStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HAProxyConfig) DeepCopyInto(out *HAProxyConfig) {
	*out = *in
	if in.PostProcessing != nil {
		in, out := &in.PostProcessing, &out.PostProcessing
		*out = make([]PostProcessorConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HAProxyConfig.
func (in *HAProxyConfig) DeepCopy() *HAProxyConfig {
	if in == nil {
		return nil
	}
	out := new(HAProxyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HAProxyGeneralFile) DeepCopyInto(out *HAProxyGeneralFile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HAProxyGeneralFile.
func (in *HAProxyGeneralFile) DeepCopy() *HAProxyGeneralFile {
	if in == nil {
		return nil
	}
	out := new(HAProxyGeneralFile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HAProxyGeneralFile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HAProxyGeneralFileList) DeepCopyInto(out *HAProxyGeneralFileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HAProxyGeneralFile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HAProxyGeneralFileList.
func (in *HAProxyGeneralFileList) DeepCopy() *HAProxyGeneralFileList {
	if in == nil {
		return nil
	}
	out := new(HAProxyGeneralFileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HAProxyGeneralFileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HAProxyGeneralFileSpec) DeepCopyInto(out *HAProxyGeneralFileSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HAProxyGeneralFileSpec.
func (in *HAProxyGeneralFileSpec) DeepCopy() *HAProxyGeneralFileSpec {
	if in == nil {
		return nil
	}
	out := new(HAProxyGeneralFileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HAProxyGeneralFileStatus) DeepCopyInto(out *HAProxyGeneralFileStatus) {
	*out = *in
	if in.DeployedToPods != nil {
		in, out := &in.DeployedToPods, &out.DeployedToPods
		*out = make([]PodDeploymentStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HAProxyGeneralFileStatus.
func (in *HAProxyGeneralFileStatus) DeepCopy() *HAProxyGeneralFileStatus {
	if in == nil {
		return nil
	}
	out := new(HAProxyGeneralFileStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HAProxyMapFile) DeepCopyInto(out *HAProxyMapFile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HAProxyMapFile.
func (in *HAProxyMapFile) DeepCopy() *HAProxyMapFile {
	if in == nil {
		return nil
	}
	out := new(HAProxyMapFile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HAProxyMapFile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HAProxyMapFileList) DeepCopyInto(out *HAProxyMapFileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HAProxyMapFile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HAProxyMapFileList.
func (in *HAProxyMapFileList) DeepCopy() *HAProxyMapFileList {
	if in == nil {
		return nil
	}
	out := new(HAProxyMapFileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HAProxyMapFileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HAProxyMapFileSpec) DeepCopyInto(out *HAProxyMapFileSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HAProxyMapFileSpec.
func (in *HAProxyMapFileSpec) DeepCopy() *HAProxyMapFileSpec {
	if in == nil {
		return nil
	}
	out := new(HAProxyMapFileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HAProxyMapFileStatus) DeepCopyInto(out *HAProxyMapFileStatus) {
	*out = *in
	if in.DeployedToPods != nil {
		in, out := &in.DeployedToPods, &out.DeployedToPods
		*out = make([]PodDeploymentStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HAProxyMapFileStatus.
func (in *HAProxyMapFileStatus) DeepCopy() *HAProxyMapFileStatus {
	if in == nil {
		return nil
	}
	out := new(HAProxyMapFileStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HAProxyTemplateConfig) DeepCopyInto(out *HAProxyTemplateConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HAProxyTemplateConfig.
func (in *HAProxyTemplateConfig) DeepCopy() *HAProxyTemplateConfig {
	if in == nil {
		return nil
	}
	out := new(HAProxyTemplateConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HAProxyTemplateConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HAProxyTemplateConfigList) DeepCopyInto(out *HAProxyTemplateConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HAProxyTemplateConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HAProxyTemplateConfigList.
func (in *HAProxyTemplateConfigList) DeepCopy() *HAProxyTemplateConfigList {
	if in == nil {
		return nil
	}
	out := new(HAProxyTemplateConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HAProxyTemplateConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HAProxyTemplateConfigSpec) DeepCopyInto(out *HAProxyTemplateConfigSpec) {
	*out = *in
	if in.LibraryRefs != nil {
		in, out := &in.LibraryRefs, &out.LibraryRefs
		*out = make([]LibraryRef, len(*in))
		copy(*out, *in)
	}
	out.CredentialsSecretRef = in.CredentialsSecretRef
	in.PodSelector.DeepCopyInto(&out.PodSelector)
	in.Controller.DeepCopyInto(&out.Controller)
	out.Logging = in.Logging
	out.Dataplane = in.Dataplane
	in.TemplatingSettings.DeepCopyInto(&out.TemplatingSettings)
	if in.WatchedResourcesIgnoreFields != nil {
		in, out := &in.WatchedResourcesIgnoreFields, &out.WatchedResourcesIgnoreFields
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.WatchedResources != nil {
		in, out := &in.WatchedResources, &out.WatchedResources
		*out = make(map[string]WatchedResource, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Validators != nil {
		in, out := &in.Validators, &out.Validators
		*out = make([]ValidatorConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TemplateSnippets != nil {
		in, out := &in.TemplateSnippets, &out.TemplateSnippets
		*out = make(map[string]TemplateSnippet, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.AbsentIncrementalGroups != nil {
		in, out := &in.AbsentIncrementalGroups, &out.AbsentIncrementalGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Maps != nil {
		in, out := &in.Maps, &out.Maps
		*out = make(map[string]MapFile, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Files != nil {
		in, out := &in.Files, &out.Files
		*out = make(map[string]GeneralFile, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.SSLCertificates != nil {
		in, out := &in.SSLCertificates, &out.SSLCertificates
		*out = make(map[string]SSLCertificate, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.K8sResources != nil {
		in, out := &in.K8sResources, &out.K8sResources
		*out = make(map[string]K8sResource, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	in.HAProxyConfig.DeepCopyInto(&out.HAProxyConfig)
	if in.ValidationTests != nil {
		in, out := &in.ValidationTests, &out.ValidationTests
		*out = make(map[string]ValidationTest, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HAProxyTemplateConfigSpec.
func (in *HAProxyTemplateConfigSpec) DeepCopy() *HAProxyTemplateConfigSpec {
	if in == nil {
		return nil
	}
	out := new(HAProxyTemplateConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HAProxyTemplateConfigStatus) DeepCopyInto(out *HAProxyTemplateConfigStatus) {
	*out = *in
	if in.LastValidated != nil {
		in, out := &in.LastValidated, &out.LastValidated
		*out = (*in).DeepCopy()
	}
	if in.ValidationErrors != nil {
		in, out := &in.ValidationErrors, &out.ValidationErrors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HAProxyTemplateConfigStatus.
func (in *HAProxyTemplateConfigStatus) DeepCopy() *HAProxyTemplateConfigStatus {
	if in == nil {
		return nil
	}
	out := new(HAProxyTemplateConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HAProxyTemplateLibrary) DeepCopyInto(out *HAProxyTemplateLibrary) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HAProxyTemplateLibrary.
func (in *HAProxyTemplateLibrary) DeepCopy() *HAProxyTemplateLibrary {
	if in == nil {
		return nil
	}
	out := new(HAProxyTemplateLibrary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HAProxyTemplateLibrary) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HAProxyTemplateLibraryList) DeepCopyInto(out *HAProxyTemplateLibraryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HAProxyTemplateLibrary, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HAProxyTemplateLibraryList.
func (in *HAProxyTemplateLibraryList) DeepCopy() *HAProxyTemplateLibraryList {
	if in == nil {
		return nil
	}
	out := new(HAProxyTemplateLibraryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HAProxyTemplateLibraryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HAProxyTemplateLibrarySpec) DeepCopyInto(out *HAProxyTemplateLibrarySpec) {
	*out = *in
	in.TemplatingSettings.DeepCopyInto(&out.TemplatingSettings)
	if in.TemplateSnippets != nil {
		in, out := &in.TemplateSnippets, &out.TemplateSnippets
		*out = make(map[string]TemplateSnippet, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Maps != nil {
		in, out := &in.Maps, &out.Maps
		*out = make(map[string]MapFile, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Files != nil {
		in, out := &in.Files, &out.Files
		*out = make(map[string]GeneralFile, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.SSLCertificates != nil {
		in, out := &in.SSLCertificates, &out.SSLCertificates
		*out = make(map[string]SSLCertificate, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.K8sResources != nil {
		in, out := &in.K8sResources, &out.K8sResources
		*out = make(map[string]K8sResource, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	in.HAProxyConfig.DeepCopyInto(&out.HAProxyConfig)
	if in.ValidationTests != nil {
		in, out := &in.ValidationTests, &out.ValidationTests
		*out = make(map[string]ValidationTest, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HAProxyTemplateLibrarySpec.
func (in *HAProxyTemplateLibrarySpec) DeepCopy() *HAProxyTemplateLibrarySpec {
	if in == nil {
		return nil
	}
	out := new(HAProxyTemplateLibrarySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HAProxyTemplateLibraryStatus) DeepCopyInto(out *HAProxyTemplateLibraryStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HAProxyTemplateLibraryStatus.
func (in *HAProxyTemplateLibraryStatus) DeepCopy() *HAProxyTemplateLibraryStatus {
	if in == nil {
		return nil
	}
	out := new(HAProxyTemplateLibraryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPResourceFixture) DeepCopyInto(out *HTTPResourceFixture) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPResourceFixture.
func (in *HTTPResourceFixture) DeepCopy() *HTTPResourceFixture {
	if in == nil {
		return nil
	}
	out := new(HTTPResourceFixture)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IncrementalTemplate) DeepCopyInto(out *IncrementalTemplate) {
	*out = *in
	if in.WhenAnyPathExists != nil {
		in, out := &in.WhenAnyPathExists, &out.WhenAnyPathExists
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Consumes != nil {
		in, out := &in.Consumes, &out.Consumes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.OptionalConsumes != nil {
		in, out := &in.OptionalConsumes, &out.OptionalConsumes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Effects != nil {
		in, out := &in.Effects, &out.Effects
		*out = make([]IncrementalEffect, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IncrementalTemplate.
func (in *IncrementalTemplate) DeepCopy() *IncrementalTemplate {
	if in == nil {
		return nil
	}
	out := new(IncrementalTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K8sResource) DeepCopyInto(out *K8sResource) {
	*out = *in
	if in.PostProcessing != nil {
		in, out := &in.PostProcessing, &out.PostProcessing
		*out = make([]PostProcessorConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CreateOnlyFields != nil {
		in, out := &in.CreateOnlyFields, &out.CreateOnlyFields
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K8sResource.
func (in *K8sResource) DeepCopy() *K8sResource {
	if in == nil {
		return nil
	}
	out := new(K8sResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LeaderElectionConfig) DeepCopyInto(out *LeaderElectionConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LeaderElectionConfig.
func (in *LeaderElectionConfig) DeepCopy() *LeaderElectionConfig {
	if in == nil {
		return nil
	}
	out := new(LeaderElectionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LibraryRef) DeepCopyInto(out *LibraryRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LibraryRef.
func (in *LibraryRef) DeepCopy() *LibraryRef {
	if in == nil {
		return nil
	}
	out := new(LibraryRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoggingConfig) DeepCopyInto(out *LoggingConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoggingConfig.
func (in *LoggingConfig) DeepCopy() *LoggingConfig {
	if in == nil {
		return nil
	}
	out := new(LoggingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MapFile) DeepCopyInto(out *MapFile) {
	*out = *in
	if in.PostProcessing != nil {
		in, out := &in.PostProcessing, &out.PostProcessing
		*out = make([]PostProcessorConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Ordered != nil {
		in, out := &in.Ordered, &out.Ordered
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MapFile.
func (in *MapFile) DeepCopy() *MapFile {
	if in == nil {
		return nil
	}
	out := new(MapFile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodDeploymentStatus) DeepCopyInto(out *PodDeploymentStatus) {
	*out = *in
	if in.Reasons != nil {
		in, out := &in.Reasons, &out.Reasons
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodDeploymentStatus.
func (in *PodDeploymentStatus) DeepCopy() *PodDeploymentStatus {
	if in == nil {
		return nil
	}
	out := new(PodDeploymentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodSelector) DeepCopyInto(out *PodSelector) {
	*out = *in
	if in.MatchLabels != nil {
		in, out := &in.MatchLabels, &out.MatchLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodSelector.
func (in *PodSelector) DeepCopy() *PodSelector {
	if in == nil {
		return nil
	}
	out := new(PodSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostProcessorConfig) DeepCopyInto(out *PostProcessorConfig) {
	*out = *in
	if in.Params != nil {
		in, out := &in.Params, &out.Params
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostProcessorConfig.
func (in *PostProcessorConfig) DeepCopy() *PostProcessorConfig {
	if in == nil {
		return nil
	}
	out := new(PostProcessorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceReference) DeepCopyInto(out *ResourceReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceReference.
func (in *ResourceReference) DeepCopy() *ResourceReference {
	if in == nil {
		return nil
	}
	out := new(ResourceReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SSLCertificate) DeepCopyInto(out *SSLCertificate) {
	*out = *in
	if in.PostProcessing != nil {
		in, out := &in.PostProcessing, &out.PostProcessing
		*out = make([]PostProcessorConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SSLCertificate.
func (in *SSLCertificate) DeepCopy() *SSLCertificate {
	if in == nil {
		return nil
	}
	out := new(SSLCertificate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretReference) DeepCopyInto(out *SecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretReference.
func (in *SecretReference) DeepCopy() *SecretReference {
	if in == nil {
		return nil
	}
	out := new(SecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerAddr) DeepCopyInto(out *ServerAddr) {
	*out = *in
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerAddr.
func (in *ServerAddr) DeepCopy() *ServerAddr {
	if in == nil {
		return nil
	}
	out := new(ServerAddr)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemplateSnippet) DeepCopyInto(out *TemplateSnippet) {
	*out = *in
	if in.Requires != nil {
		in, out := &in.Requires, &out.Requires
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Incremental != nil {
		in, out := &in.Incremental, &out.Incremental
		*out = new(IncrementalTemplate)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemplateSnippet.
func (in *TemplateSnippet) DeepCopy() *TemplateSnippet {
	if in == nil {
		return nil
	}
	out := new(TemplateSnippet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemplatingSettings) DeepCopyInto(out *TemplatingSettings) {
	*out = *in
	in.ExtraContext.DeepCopyInto(&out.ExtraContext)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemplatingSettings.
func (in *TemplatingSettings) DeepCopy() *TemplatingSettings {
	if in == nil {
		return nil
	}
	out := new(TemplatingSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValidationAssertion) DeepCopyInto(out *ValidationAssertion) {
	*out = *in
	if in.Patterns != nil {
		in, out := &in.Patterns, &out.Patterns
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValidationAssertion.
func (in *ValidationAssertion) DeepCopy() *ValidationAssertion {
	if in == nil {
		return nil
	}
	out := new(ValidationAssertion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValidationTest) DeepCopyInto(out *ValidationTest) {
	*out = *in
	if in.Fixtures != nil {
		in, out := &in.Fixtures, &out.Fixtures
		*out = make(map[string][]runtime.RawExtension, len(*in))
		for key, val := range *in {
			var outVal []runtime.RawExtension
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make([]runtime.RawExtension, len(*in))
				for i := range *in {
					(*in)[i].DeepCopyInto(&(*out)[i])
				}
			}
			(*out)[key] = outVal
		}
	}
	if in.HTTPResources != nil {
		in, out := &in.HTTPResources, &out.HTTPResources
		*out = make([]HTTPResourceFixture, len(*in))
		copy(*out, *in)
	}
	if in.CurrentServers != nil {
		in, out := &in.CurrentServers, &out.CurrentServers
		*out = make(map[string]map[string]ServerAddr, len(*in))
		for key, val := range *in {
			var outVal map[string]ServerAddr
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make(map[string]ServerAddr, len(*in))
				for key, val := range *in {
					(*out)[key] = *val.DeepCopy()
				}
			}
			(*out)[key] = outVal
		}
	}
	if in.CurrentFiles != nil {
		in, out := &in.CurrentFiles, &out.CurrentFiles
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.ExtraContext.DeepCopyInto(&out.ExtraContext)
	if in.Requires != nil {
		in, out := &in.Requires, &out.Requires
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RequiresFields != nil {
		in, out := &in.RequiresFields, &out.RequiresFields
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Assertions != nil {
		in, out := &in.Assertions, &out.Assertions
		*out = make([]ValidationAssertion, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValidationTest.
func (in *ValidationTest) DeepCopy() *ValidationTest {
	if in == nil {
		return nil
	}
	out := new(ValidationTest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValidatorConfig) DeepCopyInto(out *ValidatorConfig) {
	*out = *in
	if in.Files != nil {
		in, out := &in.Files, &out.Files
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DataFiles != nil {
		in, out := &in.DataFiles, &out.DataFiles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TimeoutMs != nil {
		in, out := &in.TimeoutMs, &out.TimeoutMs
		*out = new(int32)
		**out = **in
	}
	if in.MaxConnections != nil {
		in, out := &in.MaxConnections, &out.MaxConnections
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValidatorConfig.
func (in *ValidatorConfig) DeepCopy() *ValidatorConfig {
	if in == nil {
		return nil
	}
	out := new(ValidatorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WatchedResource) DeepCopyInto(out *WatchedResource) {
	*out = *in
	if in.APIVersions != nil {
		in, out := &in.APIVersions, &out.APIVersions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.IndexBy != nil {
		in, out := &in.IndexBy, &out.IndexBy
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.IgnoreFields != nil {
		in, out := &in.IgnoreFields, &out.IgnoreFields
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WatchedResource.
func (in *WatchedResource) DeepCopy() *WatchedResource {
	if in == nil {
		return nil
	}
	out := new(WatchedResource)
	in.DeepCopyInto(out)
	return out
}
