// Code generated by gen-validators; DO NOT EDIT.

// Copyright 2025 Philipp Hossner
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package validators

import "regexp"

// Pre-compiled regex patterns for validation.
// These are compiled once at package initialization to avoid
// repeated compilation during validation.
var (
	pattern_48e2         = regexp.MustCompile(`^(0x[0-9A-Fa-f]+|[0-9]+)$`)
	patternCaptureSample = regexp.MustCompile(`^(?:[A-Za-z]+\("([A-Za-z\s]+)"\)|[A-Za-z]+)`)
	patternResolveNet    = regexp.MustCompile(`^([A-Za-z0-9.:/]+)(,[A-Za-z0-9.:/]+)*$`)
	patternResolveOpts   = regexp.MustCompile(`^(allow-dup-ip|ignore-weight|prevent-dup-ip)(,(allow-dup-ip|ignore-weight|prevent-dup-ip))*$`)
	patternGUID          = regexp.MustCompile(`^[A-Za-z0-9-_.:]+$`)
	patternNoWhitespace  = regexp.MustCompile(`^[^\s]+$`)
)
