#!/bin/bash
# Every exact string quoted in RESULTS.md must exist verbatim in out/*.txt.
D="$(cd "$(dirname "$0")" && pwd)"
fail=0
check() {
  if grep -RqF -- "$1" "$D/out/"; then printf 'OK   %s\n' "$1"
  else printf 'MISS %s\n' "$1"; fail=1; fi
}
check "New backend registered."
check "New server registered."
check "Backend published."
check "Backend unpublished."
check "Server deleted."
check "Backend deleted."
check "Done."
check "Wait delay expired. Server still has connections attached to it, cannot remove it."
check "Interrupted. Server still has connections attached to it, cannot remove it."
check "Interrupted. (null)"
check "Error during backend creation : name is already used by other proxy 'backend dynA'."
check "Error during backend creation : name is already used by other proxy 'frontend fe'."
check "Error during backend creation : GUID insertion : duplicate entry with backend dynA."
check "Usage: add backend <name> from <defproxy>."
check "Already exists a server with the same name in backend."
check "No such backend."
check "'server' expects <name> and <addr>[:<port>] as arguments."
check "Require 'backend/server'."
check "unknown keyword 'no-such-keyword-here'."
check "unknown keyword 'init-state'."
check "'enabled' option is not accepted for dynamic server"
check "'no-check' option is not accepted for dynamic server"
check "Only servers in maintenance mode can be deleted."
check "Server still has connections attached to it, cannot remove it."
check "Backend must be unpublished prior to its deletion."
check "Only a backend without server can be deleted."
check "Failed. Only servers in maintenance mode can be deleted."
check "Failed. Backend must be unpublished prior to its deletion."
check "Failed. Only a backend without server can be deleted."
check "Can't find the target PID matching the prefix '@9'"
check "Can't find the target PID matching the prefix '@@1'"
check "Can't find the target PID matching the prefix '@1'"
check "The command line is too big for the buffer size. Please change 'tune.bufsize' in the configuration to use a bigger command."
check "Backend does not support dynamic servers : backend 'bal_static_rr' uses a non dynamic load balancing method."
check "Backend must use a dynamic load balancing to support dynamic servers."
check "'ca-file' : unable to load /cfg/tls/ca2.crt."
check "unable to stat SSL certificate '/cfg/tls/client2.pem'."
check "is explicitly referenced by another proxy and implicitly used here. To avoid any ambiguity don't mix both usage. Add a last defaults section not explicitly used or always use explicit references."
check "error detected in frontend 'fe' while parsing 'http-request set-timeout' rule : 'fe' has no backend capability."
check "Server dynP/s1 is going DOWN for maintenance. 0 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue."
check "backend 'dynP' has no server available!"
check "List of keywords supported for dynamic server:"
check "denied-by-profile"
check "pubX status=UP (UNPUB)"
check "Connection refused"
check "Success=1"
check "[6]: New backend registered."
check "[3]: Error during backend creation : name is already used by other proxy 'backend sevB'."
check "[info]: New backend registered."
check "[err]: Error during backend creation : name is already used by other proxy 'backend sevC'."
exit $fail
