#!/usr/bin/env bash
# check-test-inventory.sh — "every test must run somewhere" gate.
#
# Fails when a *_test.go file's (path, build-tag) combination is not executed
# by any CI job / Make target. A test that never runs is worse than no test:
# it encodes false confidence and rots invisibly — the gateway e2e tests were
# profile-skipped locally and executed by NO CI job for months, and their
# first-ever execution (mid-upgrade, issue #58) surfaced four stale-assumption
# failures at once. This gate makes that class of drift a lint error.
#
# The map below mirrors the execution profiles wired in Makefile /
# .gitlab-ci.yml. When you add a new test directory or build tag, wire a job
# that runs it AND extend this map in the same MR.
set -euo pipefail
cd "$(dirname "$0")/.."

fail=0

# expected_tag <path> -> the //go:build expression class this path must carry
# so that its wired runner actually compiles it.
#
# Runners (keep in sync with Makefile targets + .gitlab-ci.yml jobs):
#   (no tag)             -> `make test` (go test ./...)         [CI: test]
#   e2e                  -> `make test-e2e`                     [CI: test-e2e]
#   integration          -> `make test-integration`             [CI: test-integration]
#   acceptance           -> `make test-acceptance`              [CI: test-acceptance]
#   gateway_conformance  -> `make test-gateway-conformance`     [CI: test-gateway-conformance]
#   ingress_conformance  -> `make test-ingress-conformance`     [CI: test-ingress-conformance]
#   playground           -> `make test-playground`              [CI: test]

while IFS= read -r f; do
  # First //go:build line, stripped to the expression.
  tag="$(grep -m1 '^//go:build ' "$f" | sed 's|^//go:build ||' || true)"

  case "$f" in
    tests/e2e/*)
      want="e2e" ;;
    tests/integration/*)
      want="integration" ;;
    tests/agent/*)
      want="agentdocker" ;;
    tests/acceptance/*)
      want="acceptance" ;;
    tests/conformance/*)
      # Two suites share this directory; a file must be reachable from at
      # least one of them. Pure negations (e.g. `!ingress_conformance`)
      # are helper files compiled into the gateway suite.
      case "$tag" in
        *gateway_conformance*|*ingress_conformance*)
          continue ;;
        *)
          echo "UNWIRED: $f (tag: '${tag:-none}') — files under tests/conformance/ must carry gateway_conformance or ingress_conformance (or a negation of one) so a conformance job compiles them"
          fail=1; continue ;;
      esac ;;
    pkg/dataplane/parser/*|pkg/dataplane/validators/*|pkg/dataplane/validate_syntax_test.go|pkg/dataplane/validate_schema_test.go|pkg/generated/validators/*)
      # The client-native syntax + schema check the browser playground answers
      # `haproxy_valid` with. No production binary may link it, so it carries
      # the `playground` tag and `make test-playground` is its runner.
      want="playground" ;;
    *)
      # Unit tests (pkg/, cmd/, tests/*.go, scripts/…): run by `make test`
      # (plain `go test ./...`), which only compiles files whose build
      # expression is satisfied WITHOUT extra -tags. Negation-only
      # expressions (e.g. `!ignore_autogenerated`) satisfy that; any
      # positive custom tag means no runner ever compiles the file.
      case "$tag" in
        ""|'!'*)
          continue ;;
        race)
          # Toolchain-set tag: every -race run (make test) compiles it.
          continue ;;
        *)
          echo "UNWIRED: $f (tag: '$tag') — positive build tag outside tests/{e2e,integration,acceptance,conformance}; no Make target / CI job runs it. Wire a runner and extend scripts/check-test-inventory.sh."
          fail=1; continue ;;
      esac ;;
  esac

  # Directory with a single required tag: require exact match.
  if [ "$tag" != "$want" ]; then
    echo "UNWIRED: $f (tag: '${tag:-none}') — files under this directory must carry '//go:build $want' or the '$want' runner silently skips them"
    fail=1
  fi
done < <(git ls-files '*_test.go')

if [ "$fail" -ne 0 ]; then
  echo ""
  echo "check-test-inventory: FAILED — every test must be compiled by exactly the runner wired for its directory."
  exit 1
fi
echo "check-test-inventory: OK — every *_test.go file is wired to a runner."
