// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {haproxyTokens, trackLine} from "./haproxy-tokens.js"
export const parser = LRParser.deserialize({
  version: 14,
  states: "nQQOPOOOOOP'#Cj'#CjOOOP'#Ch'#ChQQOPOOOOOP-E6f-E6f",
  stateData: "r~OPPOQPORPOSPOTPOUPOVPOWPOXPOYPO~O",
  goto: "j_PPPPPPPPPPPP`PfQRORSRTQOR",
  nodeNames: "⚠ Newline Space TemplateTag Comment Section Directive ProxyName Number StringTok Word HAProxyConfig",
  maxTerm: 14,
  context: trackLine,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "RORO",
  tokenizers: [haproxyTokens],
  topRules: {"HAProxyConfig":[0,11]},
  tokenPrec: 0
})
