// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Newline = 1,
  Space = 2,
  TemplateTag = 3,
  Comment = 4,
  Section = 5,
  Directive = 6,
  ProxyName = 7,
  Number = 8,
  StringTok = 9,
  Word = 10,
  HAProxyConfig = 11
