// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {mapTokens, trackColumn} from "./map-tokens.js"
export const parser = LRParser.deserialize({
  version: 14,
  states: "nQQOPOOOOOP'#Cf'#CfOOOP'#Cd'#CdQQOPOOOOOP-E6b-E6b",
  stateData: "f~OPPOQPORPOSPOTPOUPO~O",
  goto: "fZPPPPPPPP[PbQRORSRTQOR",
  nodeNames: "⚠ Newline Space TemplateTag Comment MapKey MapValue MapFile",
  maxTerm: 10,
  context: trackColumn,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "RORO",
  tokenizers: [mapTokens],
  topRules: {"MapFile":[0,7]},
  tokenPrec: 0
})
