// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {textTokens, interiorTokens} from "./scriggo-tokens.js"
export const parser = LRParser.deserialize({
  version: 14,
  states: "#lQQOPOOO!WOQO'#CoO!_OQO'#CpO!fOQO'#CqOOOP'#Cu'#CuOOOP'#Cr'#CrQQOPOOOOOQ'#Cv'#CvOOOQ'#Cs'#CsO!mOQO,59ZOOOP,59Z,59ZO!tOQO,59[OOOP,59[,59[O!{OQO,59]OOOP,59],59]OOOP-E6p-E6pOOOQ-E6q-E6qOOOP1G.u1G.uOOOP1G.v1G.vOOOP1G.w1G.w",
  stateData: "#S~OPSOQSORPOSQOTRO~OVVOWVOXVOYVOZVO[VO]VO^VO_VO`VOaVO~OUYO~PcOU[O~PcOU^O~PcOUaO~PcOUbO~PcOUcO~PcO",
  goto: "!bkPPPPPPPPPPPPPPPPPPPlllpvP!U!YTSOUQUOR_UQXPQZQQ]RV`XZ]TTOU]WPQRXZ]",
  nodeNames: "⚠ Text Comment ExprOpen StmtOpen BlockOpen TagClose Keyword Bool FunctionName VariableName PropertyName String Number Operator Dot Punct Space Template Expression Statement BlockStatement",
  maxTerm: 26,
  skippedNodes: [0],
  repeatNodeCount: 2,
  tokenData: "RORO",
  tokenizers: [textTokens, interiorTokens],
  topRules: {"Template":[0,18]},
  tokenPrec: 0
})
